BonDriver_3POUT.o: BonDriver_3POUT.cpp usbdevfile.h types_u.h em287x.h tc90522.h mxl136.h \
 tda20142.h tsthread.h verstr.h message.h
message.o: message.c message.h
osdepend.o: osdepend.c osdepend.h types_u.h
usbdevfile.o: usbdevfile.c usbdevfile.h types_u.h message.h
usbops.o: usbops.c usbops.h types_u.h message.h
tsthread.o: tsthread.c usbops.h types_u.h osdepend.h tsbuff.h tsthread.h \
 message.h
em287x.o: em287x.c usbops.h types_u.h osdepend.h em287x.h em287x_usb.h \
 em287x_priv.h message.h
em287x_usb.o: em287x_usb.c osdepend.h types_u.h em287x_usb.h \
 em287x_priv.h message.h
tc90522.o: tc90522.c osdepend.h types_u.h tc90522.h message.h
mxl136.o: mxl136.c osdepend.h types_u.h mxl136.h message.h
tda20142.o: tda20142.c osdepend.h types_u.h tda20142.h message.h
